spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
  jpa:
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env:
  dev
label:
  release
